# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b83acf58b29b33a0d12ef2d1c9383beb104643432aa40776aea717835dcc635957625f2a24d70eabcc2a66bac3c5e177b6ec65af5cf5ae0b025d92909a3e88c3

test:
  secret_key_base: 1abde755db24305a9bb9630a98fcafe58ca70eb14fc16b3ab7440f22c8785e0df0c38dc117ffe0e0155fc13cf893035c5bde9900930824127842bc3911bfe569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
